# Better prefix (optional but recommended)
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# plugins
# set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
# 
# set -g @continuum-restore 'on'
# set -g @continuum-save-interval '5'

# use vim keys in copy mode
setw -g mode-keys vi

# Mouse support
set -g mouse on

# keep window names stable
set -g allow-rename off

# Faster pane switching (vim-style)
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-j select-pane -D
bind -n M-k select-pane -U

bind -r H resize-pane -L 5
bind -r L resize-pane -R 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5

# Easier splits
bind | split-window -h
bind - split-window -v

# Reload config quickly
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Start windows at 1
set -g base-index 1
setw -g pane-base-index 1

# ----- Status bar -----
set -g status-position bottom
set -g status-interval 5

set -g status-left-length 40
set -g status-right-length 100

set -g status-left "#[fg=green]#S"
set -g status-right "#[fg=yellow]%Y-%m-%d #[fg=cyan]%H:%M"

# Window appearance
setw -g window-status-format " #I:#W "
setw -g window-status-current-format "#[bold] #I:#W "

# Colors
set -g status-style "bg=black,fg=white"
setw -g window-status-current-style "fg=green,bold"

run '~/.tmux/plugins/tpm/tpm'
